### PR TITLE
Fix #1 - Don't insert code as raw text

### LINKED ISSUE #1: Don't insert code as raw text
Instead of inserting code using `<pre />` tag, include code just like PFE does (e.g using JSF function `showcase:getFileContent()`). It's much more easy to maintain _(as you don't have to do anything if files are updated really)_

### PR DESCRIPTION
**Pull request by Rapster**
There is no need to include source code anymore :wink: (xhtml or java). There is still one case this PR does not handle yet: https://www.primefaces.org/showcase/ui/csv/custom.xhtml (when javascript is included in `<ui:define name="head">` tag. The parser includes everything from `<ui:define name="implementation">` tag for now or code surrounded by `EXAMPLE-SOURCE-START`/`EXAMPLE-SOURCE-END`

### CODE REVIEW

**Comment by Rapster** [comment]
@kubrasulukan @mertsincan @onursenture @cagataycivici Let me know what you think, it can be really quick to migrate the showcase if we are several to do it. Basically, it requires to remove all the <ui:define name="source"> in the pages, but need to pay some attention though, there is always  some exceptionnal cases

**Comment by Rapster** [comment]
Any thoughts?

**Comment by Rapster** [comment]
I've been pinging the whole team on it, but no answers... So I didn't do more since. But I think it would be a good addition...

**Comment by tandraschko** [comment]
I will check that.
But i don't see any need for OmniFaces, just use FacesContext.getCurrentInstance().getApplication().evaluateExpressionGet().

**Comment by tandraschko** [comment]
which "exceptionnal cases" are left?

**Comment by Rapster** [comment]
@tandraschko I have to remember what it is, since I received no answers I didn't finish this

**Comment by Rapster** [comment]
@mertsincan I have an issue with the source code, for some reason the first line is getting shifted on the right:

image

Caused by this code (I don't know where it comes from)
image

**Comment by Rapster** [comment]
My last commit is not great... `p:cache` only cache dom and not javascript (of course...so stupid I am not to think about this earlier 😋 ). So what happened is that, once cached and page refreshed, the rendering looks good but I can't change tab... After a bit of thinking, I should cache the content of tabs and not the whole tabView. If I'm not mistaken TabView#cache feature allows to cache content on client side right?

**Comment by tandraschko** [comment]
+1 for cache the file content on the server
there is no need to use p:cache

i would even use simple hashmap instead of ehcache
we don't need cache-features, we just have 2 modes:
- ProjectStage Production: save filecontent forever in hashmap
- ProjectStage Dev: lookup each time

**Comment by Rapster** [comment]
I'd rather use a proper cache specially because:

- it offers an eviction policy, and since I'm not fully aware of how big can be this map. I'd rather play it safe
- it gives a good use case example (the previous example was not really pertinent)

There is one problem remaining, the xml (displayed as source) is not well formatted... I need to work on that.

**Comment by Rapster** [comment]
Alright, I think I'm good with this PR. Regarding the formatting, I didn't find a fancy way to format the xml properly, so I did my own formatting (not fancy at all but working, one condition though, the file has to be properly formatted)

**Comment by Rapster** [comment]
To @mertsincan @cagataycivici I guess it was expected but just in case you didn't notice, some issues with css & icons:

- Sidebar showcase
image

- TabView for showing source code
image

**Comment by Rapster** [comment]
I guess that's the kind of commit I was talking about @mertsincan ...

**Comment by Rapster** [comment]
I had to merge this PR (which is fully working) because resync to master is too much work with the coming commits

**Comment by mertsincan** [comment]
THANKS @Rapster

**Comment by mertsincan** [comment]
@Rapster, 
When I open the page, I get the following error;
```
SEVERE: Error Rendering View[/ui/panel/grid.xhtml]
javax.el.ELException: /WEB-INF/tags/tabscode.xhtml @8,45 value="#{value}": /WEB-INF/template.xhtml @52,122 value="#{s
etFilesContent(facesContext.externalContext.requestServletPath, true)}": Problems calling function [sc:getFilesConten
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:119)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:200)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:187)
        at org.primefaces.component.api.UITabPanel.getValue(UITabPanel.java:195)
        at org.primefaces.component.api.UITabPanel.createDataModel(UITabPanel.java:158)
        at org.primefaces.component.api.UITabPanel.getDataModel(UITabPanel.java:151)
        at org.primefaces.component.api.UITabPanel._validateAttributes(UITabPanel.java:681)
        at org.primefaces.component.api.UITabPanel.process(UITabPanel.java:731)
        at org.primefaces.component.api.UITabPanel.encodeChildren(UITabPanel.java:1301)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:491
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:139)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.el.ELException: /WEB-INF/template.xhtml @52,122 value="#{sc:getFilesContent(facesContext.externalCon
t.requestServletPath, true)}": Problems calling function [sc:getFilesContent]
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:119)
        at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:74)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
        ... 55 more
Caused by: javax.el.ELException: Problems calling function [sc:getFilesContent]
        at org.apache.el.parser.AstFunction.getValue(AstFunction.java:211)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
        ... 59 more
Caused by: java.lang.NullPointerException
        at org.primefaces.showcase.util.ShowcaseUtil.flatFileContent(ShowcaseUtil.java:82)
        at org.primefaces.showcase.util.ShowcaseUtil.getFilesContent(ShowcaseUtil.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.el.parser.AstFunction.getValue(AstFunction.java:199)
        ... 62 more

Oct 30, 2018 9:29:26 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: null
java.lang.NullPointerException
        at org.primefaces.showcase.util.ShowcaseUtil.flatFileContent(ShowcaseUtil.java:82)
        at org.primefaces.showcase.util.ShowcaseUtil.getFilesContent(ShowcaseUtil.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.el.parser.AstFunction.getValue(AstFunction.java:199)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
        at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:74)
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
        at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:68)
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:200)
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:187)
        at org.primefaces.component.api.UITabPanel.getValue(UITabPanel.java:195)
        at org.primefaces.component.api.UITabPanel.createDataModel(UITabPanel.java:158)
        at org.primefaces.component.api.UITabPanel.getDataModel(UITabPanel.java:151)
        at org.primefaces.component.api.UITabPanel._validateAttributes(UITabPanel.java:681)
        at org.primefaces.component.api.UITabPanel.process(UITabPanel.java:731)
        at org.primefaces.component.api.UITabPanel.encodeChildren(UITabPanel.java:1301)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1905)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1908)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:491
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:194)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:151)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:126)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
        at org.primefaces.showcase.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:32)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:139)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Rapster** [comment]
Sorry, but I'm not reproducing your problem. It works fine by me (and my branch is update)

**Comment by Rapster** [comment]
Did you make any modifications locally? If so, send me the whole file and I'll see what I can do

**Comment by tandraschko** [comment]
@Rapster 
i switched to ehcache3.x as the dependency size ehcache2 was to big (over 8mb, not it's 1.5mb)
If you would like to configure it more better, please do. I only did basic configuration

**Comment by Rapster** [comment]
Looks great :wink:

**Comment by mertsincan** [comment]
http://localhost:8080/showcase/ui/data/datatable/columns.xhtml
Does this link work for you? @Rapster @tandraschko

**Comment by tandraschko** [comment]
nope, will fix it.

**Comment by tandraschko** [comment]
fixed :P

**Comment by Rapster** [comment]
Thank you Thomas, sorry I just read my emails

**Comment by mertsincan** [comment]
Thanks @tandraschko ;) 

Also, @Rapster and @tandraschko please see; 
image

**Comment by tandraschko** [comment]
@mertsincan can you try again? i added UTF-8 encoding now

**Comment by mertsincan** [comment]
It works fine for me.

**Pull request merged**
