### PR TITLE
Fixes #63 - Timeline: add all examples from PFE

### LINKED ISSUE #63: TimeLine: Add all examples from PFE
See: https://github.com/primefaces/primefaces/issues/5143

There are many missing examples that were in the old PrimeFaces Extensions version of the Timeline.  Those examples helped explain functionality and how to use the Timeline that are now being reported as bugs because there are missing examples.

### PR DESCRIPTION
**Pull request by jasonex7**
Fixes #63

### CODE REVIEW

**Comment by jasonex7** [comment]
It's a WIP by now. Next will be "lazy loading" and later "editable events" examples.

**Comment by melloware** [comment]
Awesome!!!!

**Comment by tandraschko** [comment]
Can you resolve conflicts?

**Comment by jasonex7** [comment]
> Can you resolve conflicts?

Sure, the conflicts are now resolved.

The editable server-side example will work only if https://github.com/primefaces/primefaces/issues/5352 is fixed.

**Comment by melloware** [comment]
Is this safe to merge or are you working on more examples?

**Comment by jasonex7** [comment]
> Is this safe to merge or are you working on more examples?

It's now safe to merge.

**Pull request merged**
