### PR TITLE
Fix #4129: Add Legend customization to ChartJS models.

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by tandraschko** [comment]
I wonder if you could switch this example to automatically get the sources into the sources tabview isntead of copying it?

**Comment by melloware** [comment]
That would be great. I can modify the PR.  @Rapster do you have an example showcase page I should look at to make this happen?

**Comment by Rapster** [comment]
@mertsincan is the author of this component, he'll have a better idea than me :wink:

**Comment by melloware** [comment]
@Rapster I meant didn't you convert the showcase to pull from source instead of copying and pasting the code into th XHTML?  Right now the ChartJS examples are still copying and pasting code from the Java beans into the XHTML.  I think @tandraschko is asking to make this the other way to prevent copy and paste.

**Comment by Rapster** [comment]
In theory, you have nothing to do since the bean chartJsView is present in the xhtml. Or it does not show up?

**Comment by melloware** [comment]
Just pushed a fix. worked like a charm!  Nice work @Rapster makes the showcase way easier to maintain.

**Comment by Rapster** [comment]
Thanks Emil I'm glad to hear it :wink:

**Comment by Rapster** [comment]
Could you check the indentation please?

**Comment by melloware** [comment]
Fixed.

**Pull request merged**
