### PR TITLE
DataTable: TableState: extend clearTableState

### PR DESCRIPTION
**Pull request by christophs78**
https://github.com/primefaces/primefaces/issues/5463

### CODE REVIEW

**Comment by melloware** [comment]
Hmm should what you are doing here but done automatically by the clear() method?

**Comment by christophs78** [comment]
Yes, we may expect this, but currently the clear() method does not reset the DataTable OOTB. @Rapster said he may work on this for 9.0

**Comment by tandraschko** [comment]
i general findComponent should not be used if you have the whole clientId. invokeOnComponent should be used.

**Comment by christophs78** [comment]
@tandraschko: Feel free to modify the code the way you think. You are the expert. It´s always a pleasure to learn some of your tricks.

**Comment by tandraschko** [comment]
Danke für die Blumen :P

Please see: https://github.com/primefaces/showcase-facelift/commit/6e091942698f399c79868fa7cce7b36af45c0573

**Pull request merged**
